### DISCUSSION TITLE
Playing sound triggered by HomeAssistant?

### DISCUSSION THREAD

**Discussion by feinadam** [seaky/nspanel_pro_tools_apk#228] [General]
Hello everybody!

I'm using since years the NSpanel (predecessor of Npanel pro), with Blackymas's custom firmware.
There is a service implemented in this firmware which is able the play rtttl sounds, which I really liked.
(When somebody opens the gate, HA sent a notification sound to the NSpanel. 
I have used 3 different sound for 3 different event.)

Now I'm moving to an Nspanel Pro120.
Is there any feature or workaround to play some sound with Nspanel Pro120?

Thank you in advanced!

**Comment by thomaszlow** [comment]
You can install the HA companion app on NSPanel Pro and use the `notify` function inside an automation.
With a custom `channel` you can set up a custom MP3 that you uploaded to folder `/storage/emulated/0/Ringtones/` on your NSPanel Pro device before.
So you are able to set up as many channels as you want with different MP3 sounds.

Here is an example notification out of an automation:

```yaml
alias: NSPanel Pro - Play doorbell sound
action: notify.mobile_app_YOURDEVICENAME
data:
   data:
      channel: doorbell
   message: Doorbell
```
